### ISSUE TITLE
GVK for the object missing from the result returned

### ISSUE THREAD

**Issue by prateekgogia** [kubernetes/client-go#1004]
When using `client.Client` controller-runtime for GET objects, the result returned from client-go is missing GVK for the object.
This is how I create the client from controller-runtime.-

```
        config, err := clientcmd.BuildConfigFromFlags("", "/tmp/config")
	if err != nil {
		panic(err.Error())
	}
	kubeClient, err := client.New(config, client.Options{Scheme: scheme})
	if err != nil {
		panic(err.Error())
	}
	o := client.Object(&v1.Secret{})
	if err := kubeClient.Get(context.Background(), NamespacedName("default", "secret-name"), o); err != nil {
		panic(err.Error())
	}
	fmt.Printf("GVK for obj is  %+v", o.GetObjectKind().GroupVersionKind().String())
```
GVK is missing but the object exists.

**Comment by hakuna-matatah** [comment]
Ideally this test here should fail:
 - https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/client-go/kubernetes_test/fake_client_test.go#L90-L91
- https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/client-go/kubernetes_test/fake_client_test.go#L68-L69

It's succeeding because probably we are not comparing it appropriately like using `DeepEquals` .

Let's fix these as well as part of this Issue.
