### ISSUE TITLE
When to use Update or Patch (or Apply) for a resource?

### ISSUE THREAD

**Issue by SimonBaeumer** [kubernetes/client-go#1058]
Hey client-go community,
I recently stumbled multiple times about the question whether a resource should be patched or updated using the typed kubernetes client and could not find an answer when to use which method.

Typically I observe the usage of the `Update` over `Patch` on typed clients but don't know why.

Here an example how an updated to a secret could look like for update and patch:

**Update **

```
// Update a secret via Update
secret, _ := secretsClient.Get(ctx, "my-secret", metav1.GetOptions{})
secret.StringData["something"] = "new data"
updatedSecret, _ := secretsClient.Update(ctx, secret)
```

**Patch**

```
patch := map[string]interface{}{"Op": "replace", "Path": "/data", "Value": map[string]string{"something": "value"}}
patchBytes, _ := json.Marshal(patch)

patchedSecret, _ := r.secretsClient.Patch(ctx, "my-secret", k8sTypes.JSONPatchType, patchBytes, metav1.PatchOptions{})
```

At a first glance the patch resource looks better to me because it saves an API call to the server as only the updated data needs to be provided.
On a second glance the `Update` is declarative and feels more "kube-native" as the desired state is given to the API server.

Also there is the `Apply` function which I did not cover here.

Which of the three (apply, patch and update) is recommended to use? 
Does the client-go typed client functions compare to the `kubectl <apply|patch|create>` commands described in the [Kubernetes Object Management](https://kubernetes.io/docs/concepts/overview/working-with-objects/object-management/) article?

Thanks in advance!

cc: @juanrh

**Comment by hoklieu** [comment]
hi I'm having similar ask. Also I'm wondering what will update do in case that underlying object doesn't actually change?  What I observed is that it's trying to create something new even if the obj stays the same

**Comment by jroper** [comment]
> I imagine there could be a pitfall with Update if the resource being updated changes in between calling Get()/List() and calling Update().

This is not an issue. Kubernetes uses optimistic locking. When you update a resource, that resource must have its `resourceVersion` field set (which it will if you've fetched it from the API first). The k8s API server will check this field against what's stored, and if it doesn't match (that is, if it's been changed since that resource was fetched), the update will fail, preventing the new changes from being overwritten.

One good reason for using patch is to handle cases where the CRD itself is evolving. Let's say you add a new field to a CRD, and then you create a new client that supports updating that field. The client updates it, but let's say another person/system is using an old client that doesn't know about that field. If that client attempts to update the resource using Put, whatever was in the new field will be lost, because the old client will drop that config when it parses the resource, and then send it back to the server unset. Patch is able to mitigate this problem somewhat.

**Comment by weikaipan** [comment]
> > I imagine there could be a pitfall with Update if the resource being updated changes in between calling Get()/List() and calling Update().
> 
> This is not an issue. Kubernetes uses optimistic locking. When you update a resource, that resource must have its `resourceVersion` field set (which it will if you've fetched it from the API first). The k8s API server will check this field against what's stored, and if it doesn't match (that is, if it's been changed since that resource was fetched), the update will fail, preventing the new changes from being overwritten.
> 
> One good reason for using patch is to handle cases where the CRD itself is evolving. Let's say you add a new field to a CRD, and then you create a new client that supports updating that field. The client updates it, but let's say another person/system is using an old client that doesn't know about that field. If that client attempts to update the resource using Put, whatever was in the new field will be lost, because the old client will drop that config when it parses the resource, and then send it back to the server unset. Patch is able to mitigate this problem somewhat.

Hi @jroper , thank you for your detailed explanation. Just one question to follow up - I might overthink it, but I see that you wrote `Patch is able to mitigate this problem somewhat.`, can you share the details about why it is a mitigation rather than a solution? Thank you!
