### ISSUE TITLE
imdario reporting wrong name

### ISSUE THREAD

**Issue by stovak** [kubernetes/client-go#1273]
https://github.com/kubernetes/client-go/blob/9186f40b189c640d4188387901905c728f291f17/tools/clientcmd/client_config.go#LL33C1-L33C1

``` bash
go: github.com/imdario/mergo@v1.0.0: parsing go.mod:
        module declares its path as: dario.cat/mergo
                but was required as: github.com/imdario/mergo
```

**Comment by imdario** [comment]
@stovak I think they are going to need more context, as it seems to build fine:

![imagen](https://github.com/kubernetes/client-go/assets/163009/99c50745-1516-4c60-b74b-096376edbadb)

![imagen](https://github.com/kubernetes/client-go/assets/163009/3c4f7496-c69b-4b4b-88b0-3d5e1079d4d0)

**Comment by liggitt** [comment]
it looks like the module renamed itself when it promoted to v1.0.0

client-go still uses an earlier version, so the name is correct

there are compatibility issues / bugs in the module that have previously prevented updating to the latest version  - there is an open issue tracking removal of the dependency rather than updating it - https://github.com/kubernetes/kubernetes/issues/107499
