### ISSUE TITLE
Event recorder for node object is logging events in default namespace and not controller namespace

### ISSUE THREAD

**Issue by radramad** [kubernetes/client-go#1376]
I am using Kubernetes version 1.28,and it is a gcp cluster.

I am writing a controller using client-go package and when using event recorder its still logging in default namespace for the node object even though I explicitly specify the namespace as controller namespace.

Here is the code

`	logger := klog.FromContext(ctx)

	// Create event broadcaster
	logger.V(4).Info("Creating event broadcaster")
	eventBroadcaster := record.NewBroadcaster()
	eventBroadcaster.StartStructuredLogging(0)
	eventBroadcaster.StartRecordingToSink(&typedcorev1.EventSinkImpl{Interface: kubeClientset.CoreV1().Events("node-controller")})
	recorder := eventBroadcaster.NewRecorder(scheme.Scheme, corev1.EventSource{Component: controllerAgentName})
	ratelimiter := workqueue.NewMaxOfRateLimiter(
		workqueue.NewItemExponentialFailureRateLimiter(5*time.Second, 1000*time.Second),
		&workqueue.BucketRateLimiter{Limiter: rate.NewLimiter(rate.Limit(50), 300)},
	)`

This is logging the events for node object in default namespace but not in controller namespace even thought I explicitly specified here as namespace "node-controller",
eventBroadcaster.StartRecordingToSink(&typedcorev1.EventSinkImpl{Interface: kubeClientset.CoreV1().Events("node-controller")})

Here are the events in default namespace

```
default                    36m         Normal    Synced                             node/node1           NodeSyncedSuccessfully
default                    36m         Normal    Synced                             node/node2           NodeSyncedSuccessfully
default                    36m         Normal    Synced                             node/node3        NodeSyncedSuccessfully
```

What could be the issue here?

**Comment by sundaram2021** [comment]
The issue you're experiencing arises from how Kubernetes handles events for cluster-scoped resources like nodes. In Kubernetes, events are namespaced objects, but nodes are cluster-scoped (not tied to any namespace). When you create an event associated with a cluster-scoped resource, Kubernetes defaults the event's namespace to `"default"`, regardless of any namespace you specify in the `EventSinkImpl` or the event recorder.

**Key Points:**

1. **Cluster-Scoped Resources:** Nodes are cluster-scoped resources, meaning they are not associated with any namespace.

2. **Event Namespace Determination:** When an event is created, its namespace is determined by the namespace of the involved object:
   - For namespaced resources, the event's namespace matches that of the resource.
   - For cluster-scoped resources, the event's namespace defaults to `"default"`.

3. **EventSinkImpl Namespace:** The namespace you provide in `EventSinkImpl` (`kubeClientset.CoreV1().Events("node-controller")`) is used for the API call to create the event but does not override the event's own namespace.

**Why Your Events Appear in the Default Namespace:**

Even though you've specified the namespace `"node-controller"` in `StartRecordingToSink`, the events are associated with node objects, which are cluster-scoped. Therefore, Kubernetes defaults the event's namespace to `"default"`.

**Relevant Code Path in Kubernetes:**

When an event is recorded, the Kubernetes API server handles it as follows:

- The event's namespace is set to the involved object's namespace.
- If the involved object is cluster-scoped, the event's namespace defaults to `"default"`.

**Example from Kubernetes Source Code:**

```go
func (r *recorderImpl) makeEvent(ref *v1.ObjectReference, reason, message string) *v1.Event {
    // ...
    event.Namespace = ref.Namespace
    if event.Namespace == "" {
        event.Namespace = "default"
    }
    // ...
}
```

**Solution:**

- **Accept the Default Namespace:** Understand that events for cluster-scoped resources will always appear in the `"default"` namespace. This is by design in Kubernetes.

- **Workarounds:**
  - **Use Namespaced Resources:** If possible, associate your events with a namespaced resource.
  - **Custom Event Logging:** Instead of relying solely on Kubernetes events, consider implementing custom logging or metrics to track events in your desired namespace.

**Comment by radramad** [comment]
Ok..Can someone please give me a working example of Custom Event Logging to log cluster scoped resource events in a specific namespace? 

(Sorry to add this.. please dont get the answer directly from chatgpt. )

**Comment by sundaram2021** [comment]
hey , 

In a first look i thought that you don't understood what is happening behind the scenes in cluster .
so i tried to make you understand this with examples using chatgpt ( becuase i am very bad at documenting something i use ai for it )

........

now i have implemented the Custom Event Logging to log cluster scoped resource events in a specific namespace  using Kind Cluster . you can see it [here](https://github.com/sundaram2021/go-projects/tree/main/github-client-go)


if you want further any kind of details and guidance or information please reach out.

Thanks

**Comment by liggitt** [comment]
passing a namespace when constructing the events client `kubeClientset.CoreV1().Events("node-controller")` overrides the namespace used for normal get/list/watch/delete/deletecollection/create/update/patch operations, but does not override the namespace in methods added specifically to the event client for use by the event recorder:

https://github.com/kubernetes/kubernetes/blob/d6e5fb4a755a365e836c0898c43867f2ba414c0a/staging/src/k8s.io/client-go/kubernetes/typed/core/v1/event_expansion.go#L32-L44

The implementation of those methods pulls the namespace from the Event object passed in to the client.

You *might* be able to wrap the event client with your own implementation of the EventExpansion methods that used a fixed namespace rather than the namespace in the Event objects, and which overrode the namespace in the Event objects passed in, but that may break assumptions in the event recorder... I'm not sure
