### ISSUE TITLE
Dependency on package github.com/emicklei/go-restful/swagger which no longer exists

### ISSUE THREAD

**Issue by DMXRoid** [kubernetes/client-go#175]
There's an import of "github.com/emicklei/go-restful/swagger" in client-go/discovery that breaks b/c the swagger directory is no longer in go-restful master.
```
schiros@intrepid:~/projects/acadia/vendor$ grep -rin github.com/emicklei/go-restful/swagger
src/k8s.io/client-go/discovery/discovery_client_test.go:26:     "github.com/emicklei/go-restful/swagger"
src/k8s.io/client-go/discovery/restmapper_test.go:32:   "github.com/emicklei/go-restful/swagger"
src/k8s.io/client-go/discovery/discovery_client.go:26:  "github.com/emicklei/go-restful/swagger"
src/k8s.io/client-go/discovery/fake/discovery.go:22:    "github.com/emicklei/go-restful/swagger"
```

FWIW I'm building and vendoring w/ gb, but I'm also running into the same problem if i use go get. I can work around it by manually pointing to an older branch in my manifest, but  seems non-ideal

**Comment by caesarxuchao** [comment]
If you are using `go get k8s.io/client-go`, this shouldn't happen, because `github.com/emicklei/go-restful/swagger` is [checked](https://github.com/kubernetes/client-go/tree/master/vendor/github.com/emicklei/go-restful/swagger) in client-go's vendor directory, so `go get` won't try to download it from the source.

Not sure how `gb` works, but if you use Godep as documented in the [install.md](https://github.com/kubernetes/client-go/blob/master/INSTALL.md#godep), it will follow the [entry](https://github.com/kubernetes/client-go/blob/master/Godeps/Godeps.json#L88-L90) in Godeps.json and automatically switch to an older version of emicklei/go-restful where swagger still exists. I skimmed the manual of `gb` and unfortunately it doesn't support interpret/translate Godeps.json.

**Comment by DMXRoid** [comment]
Hrm, ok.  My problems w/ go get may have been related to the failed gb attempts then.  If it works with go get and Godep, then this is just a gb issue, not y'alls problem.
