### ISSUE TITLE
RawConfig and ClientConfig method in clientcmd.DirectClientConfig are not consistent

### ISSUE THREAD

**Issue by qiujian16** [kubernetes/client-go#220]
I might be wrong, but it seems to me that ```RawConfig``` does not consider ```overrides``` while ```ClientConfig``` does.
https://github.com/kubernetes/client-go/blob/master/tools/clientcmd/client_config.go#L104

So when I create a ```DirectClientConfig``` with ```&clientcmd.ConfigOverrides{ClusterInfo: api.Cluster{Server: masterUrl}}}``` the method ```ClientConfig()``` return the correct url, but ```RawConfig()``` does not.

**Comment by IvoGoman** [comment]
I have just stumbled across this same issue with `clientcmd.NewNonInteractiveDeferredLoadingClientConfig` which uses `DirectClientConfig` under the hood. 
When retrieving the `RawConfig` the config is first merged e.g. [merged_client_builder.go#L86-L93](https://github.com/kubernetes/client-go/blob/master/tools/clientcmd/merged_client_builder.go#L86-L93 )
However, it then returns the `DirectClientConfig.RawConfig`, which results in the Config without overrides.

The Interface `ClientConfig` implemented by `DirectClientConfig` explicitly [mentions](https://github.com/kubernetes/client-go/blob/master/tools/clientcmd/client_config.go#L63-L64) that `RawConfig(..)` should return the merged config.
Since this is quite old could you kindly confirm if this is a documentation issue or indeed a bug in the implementation? 

/reopen
