### ISSUE TITLE
[RFC] Developing in client-go directly

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/client-go#235]
The goal is to develop in client-go directly, instead of developing in k8s.io/kubernetes/staging. It has several benefits:
* Increasing development velocity. @bgrant0607 mentioned k8s.io/kubernetes had hit the speed of light of developing in a single repo.
* Getting rid of the publishing robot, which is not easy to maintain.
* Getting rid of the staging area, which is not intuitive to human or golang tools.
* Backporting new API to old branches becomes possible, though probably we should solve the problem by distributing client-gen.

@lavalamp has a great writeup on the overall [plan](https://docs.google.com/document/d/1IHTBo6Ul6TtTD87u8OVXgt-NgjgNSzE5JQKlu7nWDmw/edit#heading=h.z9ny9qqwe8dq). This issue focuses on the efforts required on the client-go side.

The prerequisites of developing in client-go are:
* Developing k8s.io/api and k8s.io/apimachinery in their own repos, otherwise we might have weird cyclic dependency.
* Setting up tests that ensures k8s.io/client-go integrates with k8s.io/kubernetes.

Regarding the tests:
* We need to lean more on unit tests
  * Measure the test coverage
  * Improve the coverage
* Run integration/e2e tests with k8s.io/kubernetes master in the presubmit CI of client-go
  * Making backwards incompatible changes becomes difficult, as outline by @lavalamp in this [doc](https://docs.google.com/document/d/1IHTBo6Ul6TtTD87u8OVXgt-NgjgNSzE5JQKlu7nWDmw/edit#heading=h.z9ny9qqwe8dq).
* Integration tests with other client-go users, e.g., service-catalog (@MHBauer), kubeadm (cc @luxas).
* An idea: we can add tests that cross validate the clients in different languages, e.g., between client-go and client-python. Specifically, we define a set of standard REST operations and execute them with client-go and client-python respectively, then compare if client-go and client-python send the same request. @mbohlool @jpbetz might be interested.
  * Might need a fake apiserver if the REST operations involves server interaction
  * Does this require client-python and client-go to be developed at the same pace?

Some open questions:
* Are there other tests we should add?
* How can we involve the community?

cc @lavalamp @ericchiang @hongchaodeng

**Comment by MHBauer** [comment]
Must have CI with core kubernetes, (and preferably some other usesrs) to make sure everything always builds. Willing to help keep svc-cat running and building against some version of this.

**Comment by luxas** [comment]
@caesarxuchao Let me know if I can help in any particular way -- interested in getting things out.

As far as I understand we'll start with k8s.io/api{,machinery}, and we'll re-vendor things in a periodic manner. As a presubmit for k8s.io/api{,machinery} there will be a job that takes k8s.io/kubernetes HEAD and k8s.io/api{,machinery} HEAD, merges the PR and vendors the new code into k8s.io/kubernetes and then runs some essential tests...

So there will be a update-vendor robot for k8s.io/kubernetes instead?

**Comment by deads2k** [comment]
> As far as I understand we'll start with k8s.io/api{,machinery}, and we'll re-vendor things in a periodic manner. As a presubmit for k8s.io/api{,machinery} there will be a job that takes k8s.io/kubernetes HEAD and k8s.io/api{,machinery} HEAD, merges the PR and vendors the new code into k8s.io/kubernetes and then runs some essential tests...

Experience dealing with this in openshift suggests that an automated workflow that attempts to merge the unstable branches of multiple repos will cause one of three things:
 1. calcification of the upstreams.  They won't be able to change in meaningful ways that are important for the health of the project.
 2. carrying upstream patches.  This is particularly insidious.  Carrying a patch can get your code ready for an upstream change without doing a full rebase.  They are pretty awful to maintain.
 3. ugly workarounds downstream.  Consumers who need behavior changes will be tempted to add "do stuff" functions to parameter lists or instead of changing the upstream will mess around inside structs to get the behavior they want.

The non-automated workflow ends up causing a lot of human maintenance time as we drift.

As I understood, @lavalamp's proposed workflow we would try to handle this similar to how openshift rebases on kubernetes.  There would be unstable branches which are periodically rebased into the unstable heads of dependent projects.  I suspect that this will become someone's full time job, but I think it avoids the automation problems at least.

@kubernetes/sig-api-machinery-misc 
@sttts @liggitt @smarterclayton as other common rebasers.
