### ISSUE TITLE
Serializing struct field to nil

### ISSUE THREAD

**Issue by kyessenov** [kubernetes/client-go#257]
Field `sizeLimit` defined here https://godoc.org/k8s.io/kubernetes/pkg/api#EmptyDirVolumeSource, can never be nil. How do I invoke the special k8s serializer to make it omit from the resulting JSON/YAML?

**Comment by mandarjog** [comment]
@jingxu97 Can you help us here?  https://github.com/kubernetes/kubernetes/commit/85f030c2aad00c54d498646e4151e7fad930c7c3

For us this breaks k8s 1.6 deployment with Istio. Details are in the referenced issue.
Thanks.

**Comment by caesarxuchao** [comment]
Why is it necessary to omit the field during marshalling? Normally adding a new field doesn't break backwards compatibility. Decoder will just ignore the unknown fields.

I also tried marshalling with the standard json encoder:
```
	e := v1.EmptyDirVolumeSource{}
	b, _ := json.Marshal(e)
	fmt.Printf("%s\n", b)
```
The output is `{"sizeLimit":"0"}`. So the problem is not related to "special k8s serializer".

**Comment by kyessenov** [comment]
Here's what happens. We take k8s objects, read them with client-go 1.7, serialize with client-go 1.7, and then send them to k8s 1.6 with `kubectl apply`. sizeLimit does not exist in k8s API definition, and the apiserver rejects our processed objects.

**Comment by caesarxuchao** [comment]
The error message pasted in https://github.com/istio/pilot/issues/975 is from kubectl, not generated by apiserver. What if you do `kubectl apply --validate=false` as suggested by the error message?

**Comment by kyessenov** [comment]
I believe it would work, but we have to support other cloud providers for now, who are still on 1.6 and have 1.6 apiservers.

**Comment by caesarxuchao** [comment]
client-go is working as expected. client-go doesn't guarantee compatibility with kubectl. 
You can try to fix that particular `sizeLimit` field, but I suspect there are more such new fields in 1.7.
I think you should avoid the round-tripping in client-go, either
* write dump server's response body to a file directly
* or use the [dynamic client](https://github.com/kubernetes/client-go/tree/master/dynamic), which umarshals to `map[string]interface{}` and won't introduce new fields.

**Comment by kyessenov** [comment]
That's unfortunate. What's your recommendation for k8s JSON processing library that's backwards compatible?

**Comment by caesarxuchao** [comment]
The golang standard library behaves the same, so i don't think there will be a library that does what you want.

Do you know why the field is not omitted even though the field has the `omitempty` tag?

**Comment by kyessenov** [comment]
omitempty cannot be applied to struct field. if it was a pointer, it would work.

**Comment by caesarxuchao** [comment]
@kyessenov indeed the API is wrong, but it has to be fixed in kubernetes rather than in client-go. According to the [api-convention.md](https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#optional-vs-required), "Therefore, we ask that pointers always be used with optional fields that do not have a built-in nil value." Hence, `SizeLimit` being a non-pointer is a bug. Could you file an issue in kubernetes, assign it to the author of that API, and request it to be cherrypicked to 1.7?
