### ISSUE TITLE
Document of dynamic client

### ISSUE THREAD

**Issue by hochuenw** [kubernetes/client-go#394]
Hi, I am trying to create one crd through `dynamic client` and `unstructured`. It would be nice if we have one example for this in `examples` For example, using them to create a normal `job`?

**Comment by nikhita** [comment]
@hochuenw We suggest to use a typed client (i.e. the generated client) instead of the dynamic client, since that has created some problems in the past. We originally had an example for the dynamic client but we moved it to use the typed client.

However, if you are interested in an example with using the dynamic client, here is an example for an older branch (before we moved the example to a typed client) - https://github.com/kubernetes/apiextensions-apiserver/tree/release-1.8/examples/client-go.

**Comment by jjqquu** [comment]
@nikhita，would you kindly elaborate on problems of using dynamic client?

Now I'm attempting to design some very flexible CRDs and want to use dynamic client to access them. 

Txs

**Comment by sttts** [comment]
> some very flexible CRDs

This sounds worrying. Even CRDs should follow [Kube API conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md).

**Comment by jjqquu** [comment]
@sttts, many thanks. I'll read and follow the conventions.

**Comment by nikhita** [comment]
Closing this since the original issue seems to be fixed. Please reopen if you still feel there is an issue.

/close

**Comment by lluunn** [comment]
Hi, could you elaborate on the potential problem?

I want to use client-go to create resources from a file (just like `kubectl create -f XX`).
What's the suggested way of doing it if not using dynamic client?

**Comment by nikhita** [comment]
I think this came up on Slack recently...

To be clear, this predated https://github.com/kubernetes/kubernetes/pull/63446. The new dynamic client is better and it is encouraged to use it. :)

**Comment by daxmc99** [comment]
@nikhita Are there docs or examples for this new dynamic client that you could point me towards?

**Comment by nikhita** [comment]
> @nikhita Are there docs or examples for this new dynamic client that you could point me towards?

PR is in progress :) https://github.com/kubernetes/kubernetes/pull/76513

**Comment by ilansh** [comment]
@nikhita Is there an example of updating custom resource status using dynamic client? should that be possible?
