### ISSUE TITLE
no field or method AnnotatedEventf

### ISSUE THREAD

**Issue by ambiknai** [kubernetes/client-go#425]
I am getting below error on line

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/container/helpers.go#L198

tests/e2e/vendor/k8s.io/kubernetes/pkg/kubelet/container/helpers.go:198:21: irecorder.recorder.AnnotatedEventf undefined (type record.EventRecorder has no field or method AnnotatedEventf)

I dont see this function defined either in the interface

https://github.com/kubernetes/client-go/blob/master/tools/record/event.go#L56

**Comment by awesomenix** [comment]
If you are trying to build kubernetes from source try setting up gopath this way

On Windows

GOPATH=<REPODIR>\src\k8s.io\kubernetes\staging;<YOURGOPATH>

On Linux

GOPATH=<DIR>/Kubernetes/src/k8s.io/kubernetes/staging:<YOURGOPATH>

On windows to get the build working I had to delete the following directories

staging/src/k8s.io/apiserver/pkg/storage
vendor/github.com/spf13

in kubernetes/src/k8.io/kubernetes

**Comment by sttts** [comment]
The publisher bot was down for a few days due to permission issues with Github. It's fixed and the client-go export is up-to-date. The interface at https://github.com/kubernetes/client-go/blob/master/tools/record/event.go#L56 has the func.

Note that there will always be a drift between the kubernetes repo and client-go master branches of a few hours. So breaking changes might make them incompatible until the next publisher run.
