### ISSUE TITLE
Where can I find the Deployments API?

### ISSUE THREAD

**Issue by Norbell** [kubernetes/client-go#44]
Hello,

I try to use Deployments, but can't find the right subpackage?
I'm really confused about which package implements which set of APIs. Where are the extension, alpha and beta  API-Objekts implemented?

When should I use:
/kubernetes
/ai
/api/v1
/unversioned 
/rest 

Thank your very much!

**Comment by caesarxuchao** [comment]
Deployments are under pkg/apis/extensions/v1beta1.

/kubernetes includes the clients, they depend on the API objects defined in pkg/api/v1 and pkg/apis/XXX/vY and pkg/api/unversioned. I think it will be your entry point when writing code, because you will use this package to talk to the api server.

pkg/api and pkg/apis/ are for internal versions of objects, used by kubernetes API server. In theory, they should *NOT* exist in the client-go repo, but because our api machinery is closely tangled with them, we cannot get rid of them at the moment.

You should be using the versioned API, e.g., objects defined in pkg/api/v1 or pkg/apis/extensions/v1beta1, etc.

In kubernetes 1.6, pkg/api/unversioned will be refactored to follow the same versioning machinery. Tracking issue is https://github.com/kubernetes/kubernetes/pull/36121.

**Comment by Norbell** [comment]
@caesarxuchao : Thank you very much. You really helped me!
Maybe this information should be in the readme. I could imagine that I'm not the only one who struggles with the package structure.
