### ISSUE TITLE
Delete K8S Job leaks the pods

### ISSUE THREAD

**Issue by jgrobbel** [kubernetes/client-go#495]
From the docs we can see this text:
https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#job-termination-and-cleanup

"When you delete the job using kubectl, all the pods it created are deleted too."

But my testing shows this is not the case going through the go client:
https://github.com/kubernetes/client-go/blob/master/kubernetes/typed/batch/v1/job.go#L140

Is this expected, in that I should clean up the pods manually?

**Comment by liggitt** [comment]
when you delete via client-go, set a propagation policy in the delete options if you want the child pods to be deleted as well.

/close

**Comment by benjaminclauss** [comment]
> when you delete via client-go, set a propagation policy in the delete options if you want the child pods to be deleted as well.
> 
> /close

Why?

https://kubernetes.io/docs/concepts/workloads/controllers/job/

>  Deleting a Job will clean up the Pods it created.

**Comment by yujen77300** [comment]
hi @benjaminclauss, 
Based on the [Kubernetes official documentation](https://kubernetes.io/docs/concepts/architecture/garbage-collection/#background-deletion), the deletion behavior is determined by the Kubernetes API server rather than client packages such as client-go. This might explain why the default propagation policy is nil in client-go - it allows the API server to determine the appropriate deletion strategy based on the resource type and existing finalizers.
