### ISSUE TITLE
Dep support for client-go

### ISSUE THREAD

**Issue by aisensiy** [kubernetes/client-go#503]
I read the [INSTALL md dep part](https://github.com/kubernetes/client-go/blob/kubernetes-1.11.3/INSTALL.md#dep-not-supported-yet). But does that mean I have to convert all the json into `[[override]]` from [Godeps.json](https://github.com/kubernetes/client-go/blob/kubernetes-1.11.3/Godeps/Godeps.json)?

**Comment by tony-haibo-zhu** [comment]
Too many days passed, is there any official scheduled for Dep support? We look forward to.

**Comment by aisensiy** [comment]
Any update?

**Comment by nikhita** [comment]
> Any update?

client-go can't move to dep until the main kubernetes repo moves to it since this repo is a copy of the code in https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/client-go.

The main repo's vendoring strategies are being discussed in https://github.com/kubernetes/kubernetes/issues/44873. Closing this issue in favour of it.

/close
