### ISSUE TITLE
Request to implement resource version behavior in fake clientset

### ISSUE THREAD

**Issue by cofyc** [kubernetes/client-go#539]
Global or per object incremental resource version.
It helps to test logic involving resource version and detect races.

**Comment by aholic** [comment]
hello
is there any better method to test data race?

**Comment by kopaygorodsky** [comment]
I also stumbled on the luck of this feature in the fake client. Did anything change during 2 years?

**Comment by wenqiq** [comment]
It`s unfortunately that the feature is not implemented. I recommend one method that maybe useful.

We can use fakeClient.AddReactor to mock the error.
For example:
https://github.com/kubernetes/kubernetes/pull/99398/files

https://github.com/antrea-io/antrea/pull/2444/files

**Comment by zeevmoney** [comment]
> It`s unfortunately that the feature is not implemented. I recommend one method that maybe useful.
> 
> We can use fakeClient.AddReactor to mock the error. For example: https://github.com/kubernetes/kubernetes/pull/99398/files
> 
> https://github.com/antrea-io/antrea/pull/2444/files

Though this issue is closed, I found a simpler way to do what @wenqiq referenced here (thanks).
If you init a fake client without `fake.NewSimpleClientset()`, then creating fake resources using the API won't work, because this func creates a clientset with a reactor that creates objects:
`cs.AddReactor("*", "*", testing.ObjectReaction(o))`

So, my solution was:

1. Create fake client using `fake.NewSimpleClientset()`.
2. Run a setupPods (in my case I needed fake pods).
3. Use client.**PrepandReactor** to mock some failure after X calls:
```go
Clientset.PrependReactor("update", "*", func(action k8stesting.Action) (handled bool, ret runtime.Object, err error) {
// ...
}
```
4. Run the code that's being tested.
