### ISSUE TITLE
Support for Network Policies

### ISSUE THREAD

**Issue by FlorianOtel** [kubernetes/client-go#57]
Hello all, 

As described in [this](https://groups.google.com/d/topic/kubernetes-dev/O-TgMlH-FAY/discussion) thread, I've discovered that the existing "client-go" package does not yet support extension methods for network policies. 

By modelling it after existing support for PodSecurityPolicy -- and some help from the main repository -- I have now implemented those methods. 

They are located in my fork here:  https://github.com/FlorianOtel/client-go

However, it seems that any PRs have to be submitted via main repo, as opposed to directly here. 

Unless otherwise advised, I will try doing so next. 

Submitting this issue here for reference. 

Thanks,

/Florian

**Comment by caesarxuchao** [comment]
Hi Florian, the reason NetworkPolicy is missing in the client-go is because this [tag](https://github.com/kubernetes/kubernetes/blob/v1.6.0-alpha.0/pkg/apis/extensions/types.go#L1008) is missing in the pkg/apis/extensions/v1beta1/types.go.

To fix it, in the main repo, 
1. add the `// +genclient=true` to pkg/apis/extensions/v1beta1/types.go.
2. run hack/update-codegen.sh
3. run hack/update-staging-client-go.sh

After the PR gets merged, the changes will be populated to client-go in 24 hours.

**Comment by FlorianOtel** [comment]
Hi, 

Kindest thanks for the guidance, much appreciated -- esp. considering this is my first K8S PR :)

I've submitted the pull request already -- it's [PR #39155](https://github.com/kubernetes/kubernetes/pull/39155)

Thanks,

/Florian
