### ISSUE TITLE
List deployments on label selectors with fake client not working for AppsV1().Deployments

### ISSUE THREAD

**Issue by apollocse** [kubernetes/client-go#579]
With Fake client, when try to list deployments on label selector with AppsV1().Deployments() is not working.
Similar call with ExtensionsV1beta1().Deployments() works perfectly fine.
Eg.
Working :- 
fake.NewSimpleClientset().ExtensionsV1beta1().Deployments(<namespace>).List(metav1.ListOptions{
		LabelSelector: "<some=label>",
	})

Not working :-
fake.NewSimpleClientset().AppsV1().Deployments(<namespace>).List(metav1.ListOptions{
		LabelSelector: "<some=label>",
	})

**Comment by liggitt** [comment]
can you provide the code for the mock deployment you are having trouble listing?

**Comment by apollocse** [comment]
It's the same in description. Working one returns valid deployment list items. Not working one returns nil.

**Comment by liggitt** [comment]
can you provide the content of the deployments in question (specifically, whether they include labels in their objectmeta.labels field)

**Comment by robbie-demuth** [comment]
I ran into this issue today, but with StatefulSets. I think the issue is that the fake client doesn't support using labels when performing list requests. Instead, it returns all objects of the given type within the specified namespace. This is documented on the internal [ObjectTracker](https://godoc.org/k8s.io/client-go/testing#ObjectTracker) type and appears to be tracked by https://github.com/kubernetes-sigs/controller-runtime/pull/410
