### ISSUE TITLE
versioning: this repo is weird to use with godocs and glide

### ISSUE THREAD

**Issue by philips** [kubernetes/client-go#58]
Using this repo with glide is super bizarre UX. When I pin it to 

Essentially the workflow works like this:

- Visit godoc.org/k8s.io/client-go, see functions I want
- glide get k8s.io/client-go
- glide asks me if I want to use v1.5 release b/c it is tagged
- Try to import k8s.io/client-go/dynamic and it doesn't exist

Can we put the v1.4, v1.5, etc dirs into the master branch as well? Otherwise this UX is really confusing when compared to every other Go library.

**Comment by justinsb** [comment]
Did you see #9?

Also, try bazel :-)

**Comment by philips** [comment]
@justinsb how does bazel help with vendoring?

**Comment by philips** [comment]
@justinsb Yes, I followed the discussion in #9 and the in-person discussions in the past as well.

But, this week I have watched two developers fail at using glide + client-go and I think we should address the issue. I am seriously confused at how we ended up with both branches/tags and a folder.

**Comment by caesarxuchao** [comment]
Sorry, I'm still OOO so I might disappear after this reply.

New releases won't have folders, so glide and godoc will be consistent. v1.4 and v1.5 had folders because they started like that, and we decided to keep them that way to avoid breaking existing users at that time.

I would recommend tracking v2.0.0-alpha.1. It's cut when k8s v1.5.1 was cut. I don't think we'll make breaking changes to v2. In other words, if there are breaking changes, we'll create v3 tags.

**Comment by philips** [comment]
@caesarxuchao OK, closing this.
