### ISSUE TITLE
How can I disable klog output?

### ISSUE THREAD

**Issue by qeesung** [kubernetes/client-go#610]
Client-go always outputs a lot of unnecessary logs， Like the following

```
E0529 09:26:16.674605   39112 v2.go:105] sockjs: session not in open state
E0529 09:26:16.715718   39112 v2.go:147] sockjs: session not in open state
```

How can I disable the output?

**Comment by ofen** [comment]
I think default forced logging should be disabled to let users choose whether they need

**Comment by ofen** [comment]
If some will looking for workaround

```go
func loadKubeconfig(kubeconfig string) (*rest.Config, error) {
	if kubeconfig != "" {
		kubeconfigBytes, err := ioutil.ReadFile(kubeconfig)
		if err != nil {
			return nil, err
		}

		return clientcmd.RESTConfigFromKubeConfig(kubeconfigBytes)
	}
	return rest.InClusterConfig()
}
```

**Comment by kenchan0130** [comment]
I encountered this problem.

In my case, I sometimes get the following error message in https://github.com/kubernetes/client-go/blob/master/tools/leaderelection/leaderelection.go#L330 via https://github.com/kubernetes-sigs/aws-load-balancer-controller like:

```log
E0922 09:08:30.126551       1 leaderelection.go:320] error retrieving resource lock kube-system/aws-load-balancer-controller-leader: etcdserver: leader changed
```

However, since there is no problem on the caller side, I would like to ignore this log.
