### ISSUE TITLE
How to solve this too few arguments problem?

### ISSUE THREAD

**Issue by qinshuaihua** [kubernetes/client-go#723]
I try to run the example codes out-of-configure with client-go@kubernetes-1.14.3，I try to use the command go build . to generate the app, but I find an error:
../../go/pkg/mod/k8s.io/client-go@v11.0.1-0.20190606204521-b8faab9c5193+incompatible/rest/request.go:598:31: 
 not enough arguments in call to watch.NewStreamWatcher
        have (*versioned.Decoder)
        want (watch.Decoder, watch.Reporter)
![2019-12-08 16-32-00 的屏幕截图](https://user-images.githubusercontent.com/34976119/70386818-7b457000-19d8-11ea-9778-7af2f9124697.png)

**Comment by dickmao** [comment]
By default, go-mod is getting "latest", which is "v11+incompatible".  Whoever named that tag knew "latest" wasn't going to work.

I dialed back my versions to 0.x.y to fall under my kubernetes version 1.x.y.

Since my k8s version is 1.16.2, I did:
`go get k8s.io/apimachinery@v0.15.8-beta.0`
`go get k8s.io/client-go@v0.15.8-beta.0`

**Comment by liggitt** [comment]
this is a duplicate of https://github.com/kubernetes/client-go/issues/691#issuecomment-535426503

The solution is to ensure you are using matching levels of k8s.io/{client-go,api,apimachinery} in your go.mod file, e.g.:

```
require (
  k8s.io/api v0.17.3
  k8s.io/apimachinery v0.17.3
  k8s.io/client-go v0.17.3
)
```
