### ISSUE TITLE
can't find package auditregistration/v1alpha1

### ISSUE THREAD

**Issue by tarekesmail** [kubernetes/client-go#862]
when i trying to build my code this message appear

../../pkg/mod/k8s.io/client-go@v11.0.0+incompatible/kubernetes/scheme/register.go:26:2: module k8s.io/api@latest found (v0.19.0), but does not contain package k8s.io/api/auditregistration/v1alpha1

My go.mod file contains 

module kubernetes-go

go 1.15

require (
	github.com/imdario/mergo v0.3.11 // indirect
	golang.org/x/time v0.0.0-20200630173020-3af7569d3a1e // indirect
	k8s.io/api v0.19.0
	k8s.io/apimachinery v0.19.0
	k8s.io/client-go v11.0.0+incompatible
	k8s.io/klog v1.0.0 // indirect
	k8s.io/utils v0.0.0-20200821003339-5e75c0163111 // indirect
)

**Comment by liggitt** [comment]
You need to use a matching level of client-go and api, e.g. `k8s.io/client-go v0.19.0`

**Comment by liggitt** [comment]
See https://github.com/kubernetes/client-go/blob/master/INSTALL.md for setup details

**Comment by tarekesmail** [comment]
> See https://github.com/kubernetes/client-go/blob/master/INSTALL.md for setup details

Thanks for helping me, you saved my day, please i need to make the authentication using variables that's hold the CA, Token instead of authentication by kubeconfig file can you help me ?

Thanks in advance

**Comment by liggitt** [comment]
The examples show loading a config from a file, then using it to construct a client:

https://github.com/kubernetes/client-go/blob/master/examples/out-of-cluster-client-configuration/main.go#L52

You can construct that config struct directly instead of loading it from a kubeconfig file, and populate it with the hostname, CA, and token or client cert credentials, then continue constructing the client normally.

**Comment by tarekesmail** [comment]
@liggitt , thanks for your fast reply, i tried to this many times and i spent lot of time in this, but no chance to did it, can you please give me example using this method 

Thanks in advance for your effort and time
