### ISSUE TITLE
errors.IsNotFound not working correctly with client-go

### ISSUE THREAD

**Issue by krmayankk** [kubernetes/client-go#89]
I am using client-go by doing the following imports:-

```
"k8s.io/apimachinery/pkg/api/errors"
v1 "k8s.io/client-go/pkg/api/v1"
```

When i query a deployment which doesn't exist, i see the following in the logs:-

```
I0202 10:13:25.598285       1 round_trippers.go:417] GET https://<some ip>/apis/extensions/v1beta1/namespaces/e2e-mayank-kumar-csc-sam/deployments/default 404 Not Found in 109 milliseconds
```

404 tells me its not found

```
I0202 10:13:25.598981       1 rollout.go:138] error found deployments.extensions "default" not found
I0202 10:13:25.599018       1 rollout.go:141] not not found deployments.extensions "default" not found
```
where the exact err i get from the client-go api is `deployments.extensions "default" not found`

When i use errors.IsNotFound(err) from the apimachinery, the check fails and it doesn't identify this error as not found error.
Am  i missing anything ?

**Comment by ericchiang** [comment]
@krmayankk this is likely due to version skew between your version of apimachinery and client-go. Please take a look at this comment here: https://github.com/kubernetes/client-go/issues/83#issuecomment-280135738

We strongly recommend using a tool like `glide` to manage your dependencies: https://github.com/Masterminds/glide

Does this code if you do that?

**Comment by krmayankk** [comment]
I am doing a go get, and using glide to get dependencies for my app. But i am not using a specific branch of client-go

**Comment by ericchiang** [comment]
@krmayankk you should be using glide to manage client-go. client-go is sensitive to the versions of the packages it imports. However client-go only recently started pinning `k8s.io/apimachinery` https://github.com/kubernetes/client-go/issues/83#issuecomment-280135738 so you'll need to use a recent SHA.

**Comment by danielwhatmuff** [comment]
I am using `go deps` and have the same issue. All expected errors such as `AlreadyExists` and `NotFound` don't get detected by the functions which should return true. 

My imports...
```
"k8s.io/client-go/kubernetes"
"k8s.io/client-go/rest"
v1 "k8s.io/client-go/pkg/api/v1"
```

Example...
```
	namespace, err := clientset.CoreV1().Namespaces().Create(&v1.Namespace{
		ObjectMeta: v1.ObjectMeta{
			Name: namespaceName,
		},
	})
	if errors.IsNotFound(err) {
                // This doesnt happen...
		log.Printf("Not found")
	}
```

**Comment by Asgoret** [comment]
`errors.IsAlreadyExists(err)` doesn't work at all. Is there any abstract workaround hot to check is object exist or not?

**Comment by franpog859** [comment]
Is there any issue regarding the `errors.IsAlreadyExists(err)` mentioned by @Asgoret ? Does anyone work on that?

**Comment by scbizu** [comment]
For those who encounter with this issue , you can check whether your k8s version is equal to your client-go's version .

**Comment by vsoch** [comment]
> For those who encounter with this issue , you can check whether your k8s version is equal to your client-go's version .

Can you give an example of what you mean? I'm running into this issue (still haven't fixed it) and it's not clear if you mean the Kubernetes cluster version (which I largely can't control which version someone is using for my operator) or a package I'm using. Thanks!

**Comment by vsoch** [comment]
Coming back over a year later (and making a new operator for a different project) - my understanding of the above is that `"k8s.io/apimachinery/pkg/api/errors"` is the correct import, and when versions are matching, you don't get errors. I did this just now and looks to be working, although have not tested everything fully yet. 

It's very funny I found this original issue because I ran into a similar bug (again) that was reported here, but this time from using a different import for errors, which was my previous "solution" ! :laughing:
