### ISSUE TITLE
Delete Deployment / ReplicaSet not working

### ISSUE THREAD

**Issue by stevesloka** [kubernetes/client-go#91]
I'm developing a client which is consuming the k8s using the client-go. I'm creating Deployments with the client and they work great, but when I try and delete, the deployments delete but the pods stay running. 

I've also added logic to delete the ReplicaSets and they delete, but the pods still stay running. 

I'm currently using tag v2.0.0-alpha.1

**Comment by lavalamp** [comment]
What version of Kubernetes is the cluster are you running against? Until
the deployment controller begins using the GC, you'll need to scale the
deployment to zero before deleting it. That change should be in 1.6 if it
didn't make 1.5.

**Comment by stevesloka** [comment]
Right now I'm on v1.5.1. I can try scaling to zero first.

**Comment by lavalamp** [comment]
Yeah, I think it may have just missed the 1.5 cut.

**Comment by stevesloka** [comment]
Thanks for the help @lavalamp that worked by scaling it down first. I had to do the same for my StatefulSet as well.

**Comment by lavalamp** [comment]
Great! Just to repeat myself, this is an API thing, not a client thing. The
API ought to do what people expect after using kubectl, but it doesn't
(because kubectl manually does two things). This should be significantly
ameliorated once all the controller types use the GC. Currently I think
only RS/RC do so.
