### ISSUE TITLE
[post-1.20] Fake Dynamic Client requires scheme registration with listType, breaks duck typing.

### ISSUE THREAD

**Issue by n3wscott** [kubernetes/client-go#949]
we in Knative attempted to update to k8s client-go 1.20 and found that the fake dynamic client no longer works with duck typing because of this addition: https://github.com/kubernetes/client-go/commit/20c034c1785b34a893f7f96d91e5b849ac52ff31#diff-8ba8eeecc835702a1f7fbb6d06b268cb17453f82c5ef5c8294f25fcdf0f53dacR316-R318 @deads2k I will keep looking at the impl, but I fail to see how the dynamic client is useful if scheme registration is required, it means you can not use the dynamic client for unknown types?

it does not look like ListType is even required to list in the dynamic client: https://github.com/kubernetes/client-go/blob/f6ce18ae578c8cca64d14ab9687824d9e1305a67/dynamic/simple.go#L253-L275

unknown list types should be `*unstructured.UnstructuredList` and I think the change to fake dynamic client is an error/bug.

It does not make sense to require scheme registration with the dynamic client, the whole point is it is dynamic right?

Knative issue: https://github.com/knative/eventing/issues/5185

**Comment by deads2k** [comment]
A few points
1. this is the fake client
2. This isn't requiring a scheme registration.  
3. Since the listkind is provided by the server in the real client, it provides data that is missing in the fake client.  Missing this data causes problems of consistency when testing with fake client
4. A fake client used in a unit test is a constrained view of reality that must be predicted in order to write an effective test.  Thus asking for this mapping when creating a fake client is reasonable.

I'm open to allowing this to be specified via function if you like, but the data needs to be returned by the fake client to have parity with the real client, so I don't see an effective way to simply stop requiring this mapping.

**Comment by deads2k** [comment]
> I'm open to allowing this to be specified via function if you like, but the data needs to be returned by the fake client to have parity with the real client, so I don't see an effective way to simply stop requiring this mapping.

I'm open to a PR to make the dynamic client take a mapping function instead of a static mapping.  But we have to return the objectmeta on the list  values returned from the fake dynamic client.

**Comment by n3wscott** [comment]
oh, I see. There is a new method I should be using, the old method will not work with List.

```
func NewSimpleDynamicClientWithCustomListKinds(scheme *runtime.Scheme, gvrToListKind map[schema.GroupVersionResource]string, objects ...runtime.Object) *FakeDynamicClient {
```

**Comment by n3wscott** [comment]
OK, followup, there is code in the original `NewSumpleDynamicClient` that will look at the scheme registered does explode out the ListKinds. So if you need to work with duck types with the Fake Dynamic Client, you have to register the List Kind:

```
scheme.AddKnownTypeWithName(schema.GroupVersionKind{Group: "example.com", Version: "v1", Kind: "FooBarList"}, &unstructured.UnstructuredList{})
```

/close
