### ISSUE TITLE
testing fixture should support types.ApplyPatchType

### ISSUE THREAD

**Issue by hypergig** [kubernetes/client-go#992]
Currently all the fake clients leverage these fixtures:

https://github.com/kubernetes/client-go/blob/master/testing/fixture.go#L151-L184

Which are super great and helpful, but there is a new patch type in town and these fixtures don't know about it:

```
 types.ApplyPatchType
```
or
```
application/apply-patch+yaml
```

This leads to tests that perform server side applies to fail with `PatchType is not supported`. Support for SSA should be added to this fixture.

**Comment by Karthik-K-N** [comment]
I would like to add  `types.ApplyPatchType` into fixtures, Where can i find more info on  `types.ApplyPatchType` so that i can update the file accordingly

**Comment by grishy** [comment]
I think it's same?
https://github.com/kubernetes/client-go/issues/970

**Comment by Karthik-K-N** [comment]
Yeah, It will fix  #970 as well

**Comment by apelisse** [comment]
So if I'm looking at the [test code](https://github.com/kubernetes/client-go/blob/master/testing/fixture.go#L151-L184), I notice that we need to implement merging (i.e. decoding the patch and applying the patch, since that's what the other patch methods do) for the Apply patchtype.

The logic to do that in the apiserver is set-up here: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/patch.go#L470-L500

Mainly this code (decoding and applying):
```golang
	patchObj := &unstructured.Unstructured{Object: map[string]interface{}{}}
	if err := yaml.Unmarshal(p.patch, &patchObj.Object); err != nil {
		return nil, errors.NewBadRequest(fmt.Sprintf("error decoding YAML: %v", err))
	}

	obj, err := p.fieldManager.Apply(obj, patchObj, p.options.FieldManager, force)
	if err != nil {
		return obj, err
	}
```

The decoding is fairly straightforward, but the applying leads to a few questions:
1. how do you get the fieldManager? I suspect it could live in the [`ObjectTracker`](https://github.com/kubernetes/client-go/blob/master/testing/fixture.go#L198-L209)
    a. You'll need the openapi schema to create the fieldmanager, how do you get that openapi? Not sure yet.
    b. the `fieldManager` object has a lot of fields for conversion, not sure how available these will be.
2. Where are the options like `FieldManager` and `Force` come from? They are significant enough that you can't really skip these, I don't have an answer to this.

**Comment by Karthik-K-N** [comment]
Thanks @apelisse for your inputs, Instead of handling the patch here in client-go, How about creating a util package as like [stratergicmergepatch](https://github.com/Karthik-K-N/client-go/blob/b7e5fce706473ad4b16f6de0573723deaa0fd847/testing/fixture.go#L175) and utilizing it over here, Is this sound good.

**Comment by stevekuznetsov** [comment]
@apelisse 
>Where are the options like FieldManager and Force come from? They are significant enough that you can't really skip these, I don't have an answer to this.

These can be taken from `metav1.PatchOptions{}` as normal in the client's patch call, so at least that's the easy part.

**Comment by stevekuznetsov** [comment]
A quick read of the constructors here shows that OpenAPI + a scheme should be sufficient-ish to get this working, I think.

**Comment by apelisse** [comment]
@justinsb is working on doing something somewhat similiar in https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/270. I think we should do something that can be re-used throughout.

We would also probably need to revive/finish https://github.com/kubernetes/kubernetes/pull/87872 so that getting the openapi into the right format would be easier.

**Comment by sbueringer** [comment]
/reopen
/remove-lifecycle rotten

(I assume this was the intention)

**Comment by pohly** [comment]
/cc
/remove-lifecycle rotten

Shouldn't this issue be over in k/k? That's where the code gets developed.

**Comment by jordan-da** [comment]
> /cc /remove-lifecycle rotten
> 
> Shouldn't this issue be over in k/k? That's where the code gets developed.

🤷 sure?

should this repo have issues enabled then because it's just a gen stage?
